#! /bin/bash
USERNAME=$USER

#Anlegen des Hauptordners im Homeverzeichniss des aktuell angemeldeten users
cd ~
mkdir Axians-Networksurveillance
cd Axians-Networksurveillance

#Anlegen aller Verzeichnisse für die logs und scripte
mkdir external_ping_logs
mkdir internal_ping_logs
mkdir ulm_ping_logs
mkdir scripts

#Anlegen der Scripte
cd scripts

mkdir tmp

	#cat > network_test_extern.sh		<- Debug
	touch network_test_extern.sh

	#cat > network_test_intern.sh		<- Debug
	touch network_test_intern.sh
	
	#cat > network_test_ulm.sh		<- Debug
	touch network_test_ulm.sh
	
#Ping extern
echo "#! /bin/bash
set -xv

ping -c 5 8.8.8.8 > ./tmp/extping_1.log

sed -i '1 d' ./tmp/extping_1.log
sed -i '$ d' ./tmp/extping_1.log
sed -i '$ d' ./tmp/extping_1.log
sed -i '$ d' ./tmp/extping_1.log

DATE=$(date +"%d.%m.%Y_%H:%M:%S")


echo "-----------------------------------------" >> ./tmp/extping_2.log
echo $DATE >> ./tmp/extping_2.log
cat  ./tmp/extping_1.log >> ./tmp/extping_2.log
echo "-----------------------------------------" >> ./tmp/extping_2.log

FILENAME=$(date +"%m.%Y")

cat ./tmp/extping2.log >> ./external_ping_logs/$FILENAME.log
echo 
exit 0" >> network_test_extern.sh

#Ping intern
echo "#! /bin/bash
set -xv

ping -c 5 10.120.14.101 > ./tmp/intping.log

sed -i '1 d' ./tmp/intping_1.log
sed -i '$ d' ./tmp/intping_1.log
sed -i '$ d' ./tmp/intping_1.log
sed -i '$ d' ./tmp/intping_1.log

DATE=$(date +"%d.%m.%Y_%H:%M:%S")


echo "-----------------------------------------" >> ./tmp/intping_2.log
echo $DATE >> ./tmp/intping_2.log
cat  ./tmp/intping_1.log >> ./tmp/intping_2.log
echo "-----------------------------------------" >> ./tmp/intping_2.log

FILENAME=$(date +"%m.%Y")

cat ./tmp/intping2.log >> ./internal_ping_logs/$FILENAME.log
echo 
exit 0" >> network_test_intern.sh

#Ping ulm
echo "#! /bin/bash
set -xv

ping -c 5 10.111.4.105  > ./tmp/ulmping.log

sed -i '1 d' ./tmp/ulmping_1.log
sed -i '$ d' ./tmp/ulmping_1.log
sed -i '$ d' ./tmp/ulmping_1.log
sed -i '$ d' ./tmp/ulmping_1.log

DATE=$(date +"%d.%m.%Y_%H:%M:%S")


echo "-----------------------------------------" >> ./tmp/ulmping_2.log
echo $DATE >> ./tmp/ulmping_2.log
cat  ./tmp/ulmping_1.log >> ./tmp/ulmping_2.log
echo "-----------------------------------------" >> ./tmp/ulmping_2.log

FILENAME=$(date +"%m.%Y")

cat ./tmp/ulmping2.log >> ./ulm_ping_logs/$FILENAME.log
echo 
exit 0" >> network_test_ulm.sh

#exit
cd ..

#scripte zum cronfile hinzufügen um regelmäßige ausführung zu gewährleisten
echo "30 * * * * ~/Axians-Networksurveillance/scripts/network_test_extern.sh
30 * * * * ~/Axians-Networksurveillance/scripts/network_test_intern.sh
30 * * * * ~/Axians-Networksurveillance/scripts/network_test_ulm.sh" >> /var/spool/cron/crontabs/$USERNAME

#last info
echo If you ran this Script as Administator/root/SU everything SHOULD have worked and your maschine schould check all 3 IP Adresses frequently. HOWEVER, you now need to restart your maschine or at least the Cron Service/programm to make all scripts work as intendet: You can do this by entering '/etc/init.d/crond restart' or 'service crond restart' or 'systemctl restart crond.service'. Proceed as you wish. GL HF.

